variables:
  IMAGE: tarampampam/node:alpine

stages:
  - test
  - docs
  - deploy

before_script:
  - yarn install

# Unit tests
unit tests:
  stage: test
  image: $IMAGE
  script:
    - npm run test:unit

# Test TSLint
lint:
  stage: test
  image: $IMAGE
  script:
    - npm run test:lint

# Test TypeScript
ts:
  stage: test
  image: $IMAGE
  script:
    - npm run test:ts

# Documentation
pages:
  image: $IMAGE
  only:
    - master
  stage: docs
  script:
    - yarn docs
  artifacts:
    paths:
      - public

# Major release
release major:
  extends: .release
  variables:
    NPM_RELEASE_VERSION: major

# Minor release
release minor:
  extends: .release
  variables:
    NPM_RELEASE_VERSION: minor

# Patch release
release patch:
  extends: .release
  variables:
    NPM_RELEASE_VERSION: patch

# Release
.release:
  stage: deploy
  image: $IMAGE
  when: manual
  tags:
    - newton # tag is required for proper SSH key access (it's run on private machine)
  only:
    - master
  script:
    # Build
    - yarn build

    # Configure Git
    - git config --global user.name "Soanvig"
    - git config --global user.email "soanvig@gmail.com"

    # Prepare version
    - yarn version --$NPM_RELEASE_VERSION
    - GIT_SSH_COMMAND='ssh -i /ssh_keys/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=no' git push --follow-tags git@gitlab.com:soanvig/binary-pipe.git HEAD:$CI_COMMIT_REF_NAME

    # Save npm token and publish
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN">$HOME/.npmrc
    - npm publish dist
